name: t1

services:
  controller:
    image: mick0974/a13:t1-g11
    container_name: t1-controller
    restart: always
    expose:
      - 8081
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      # Variabili d'ambiente per PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://t1-postgres-db:5432/manvsclass
      SPRING_DATASOURCE_USERNAME: t1-g11
      SPRING_DATASOURCE_PASSWORD: 947!"p1Yv;qf
    depends_on:
      - postgres-db
      - mongo_db
    volumes:
      - ./FilesUpload:/Files-Upload
      - VolumeT0:/VolumeT0
    networks:
      - global-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo_db:
    image: "mongo:6.0.6"
    container_name: t1-mongo_db
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_volume:/data/db
    networks:
      - global-network

  postgres-db:
    image: "postgres:14-alpine3.17"
    container_name: t1-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
        - "5433:5432"
    expose:
      - "5432:5432"
    volumes:
      - postgres_data_t1:/var/lib/postgresql/data
    networks:
      - global-network

networks:
  global-network:
    external: true

volumes:
  VolumeT0:
    external: true
  postgres_data_t1:
  mongodb_data_volume: